
String style =
    "<style>"
    "   :root {"
    "   --gray-900: #111827;"
    "   --gray-800: #1F2937;"
    "   --gray-700: #374151;"
    "   --gray-600: #4B5563;"
    "   --gray-500: #6B7280;"
    "   --gray-400: #9CA3AF;"
    "   --gray-300: #D1D5DB;"
    "   --gray-200: #E5E7EB;"
    "   --gray-100: #F3F4F6;"
    "   --gray-50: #F9FAFB;"
    "   --red-500: #EF4444;"
    "   --green-500: #22C55E;"
    "   --yellow-400: #FACC15;"
    "   --blue-400: #38BDF8;"
    "   --lime-200:#ECFCCB;"
    "   --container-radius:10px;"
    "   --container-gap:10px;"
    "   --button-radius:10px;"
    "   --button-padding:10px;"
    "   --padding-min:5px;"
    "   --padding-medium:10px;"
    "   --padding-max:20px;"
    "   }"
    "   body {"
    "       padding: 0;"
    "       margin: 0;"
    "       background-color: var(--gray-900);"
    "       width: 100vw;"
    "       color:var(--lime-200);"
    "   }"
    "   p{"
    "       padding: 0;"
    "       margin: 0;"
    "   }"
    "   .dark {"
    "       background-color: var(--gray-900);"
    "   }"
    "   .flex {"
    "       display: flex;"
    "   }"
    "   .p-min {"
    "       padding: var(--padding-min)"
    "   }"
    "   .flex-1 {"
    "       flex: 1;"
    "   }"
    "   .flex-col {"
    "       flex-direction: column;"
    "   }"
    "   .items-center{"
    "       align-items: center;"
    "   }"
    "   .justify-center {"
    "       justify-content: center;"
    "   }"
    "   .h-max{"
    "       height: 100vh;"
    "   }"
    "   .w-full {"
    "       width: 100%;"
    "   }"
    "   "
    "   .border {"
    "       border-style: solid;"
    "       border-width: 1px;"
    "       border-color: var(--gray-400);"
    "   }"
    "   .button-radius {"
    "         border-radius: var(--button-radius);"
    "   }"
    "   .container {"
    "       gap: var(--container-gap);"
    "       width: 50%;"
    "       border-radius: var(--container-radius);"
    "   }"
    "   .main {"
    "       padding: 10px;"
    "       gap: var(--container-gap);"
    "   }"
    "   .title {"
    "       color: var(--lime-200);"
    "       text-align: center;"
    "   }"
    "   .button {"
    "       border-radius: var(--button-radius);"
    "       border: none;"
    "       padding-top: var(--padding-min);"
    "       padding-bottom: var(--padding-min);"
    "       padding-left:var(--padding-max) ;"
    "       padding-right:var(--padding-max) ;"
    "   }"
    "   .btn-white {"
    "       background-color: var(--gray-100);"
    "       color: var(--gray-900);"
    "   }"
    "   .btn-red {"
    "       background-color: var(--red-500);"
    "       color: var(--gray-50);"
    "   }"
    "   .btn-green {"
    "       background-color: var(--green-500);"
    "       color: var(--gray-50);"
    "   }"
    "   .info {"
    "       background-color: var(--gray-100);"
    "       color: var(--gray-800);"
    "       padding-top: var(--padding-min);"
    "       padding-bottom: var(--padding-min);"
    "       padding-left: var(--padding-max);"
    "       padding-right: var(--padding-max);"
    "       "
    "   }"
    "   .form-input{"
    "       border: none;"
    "       border-radius: 0;"
    "       background-color: var(--gray-100);"
    "       width: 70px;"
    "       outline: none;"
    "       padding-top: var(--padding-min);"
    "       padding-bottom: var(--padding-min);"
    "   }"
    "   @media only screen and (max-width: 600px) {"
    "       .container {"
    "               width: 95%;"
    "           }"
    "       }"
    "</style>";

const String mainPage =
    "<html>"
    "<head>"
    "    <meta charset='utf-8'>"
    "    <meta name='viewport' content='width=device-width, initial-scale=1'>"
    "    &&style"
    "</head>"
    "<body>"
    "    <div class='h-max flex dark items-center flex-col main'>"
    "        <h1 class='title'>Still Temp Monitor</h1>"
    "         <div id='alert' class='p-min' style='border-radius: 10px;'>"
    "                <p id='sensorData'>Still Temp Monitor</p>"
    "         </div>"
    "        <a href='introductions'>"
    "            <button class='button btn-white'>"
    "                Introductions"
    "            </button>"
    "        </a>"
    "        <div class='border w-full container flex flex-col p-min'>"
    "            <div class='flex items-center p-min' style='border-bottom: 1px solid var(--gray-200); gap: 5px;'>"
    "                <h1 class='flex-1'>Still Temp</h1>"
    "                <div class='flex items-center' style='justify-content: space-around; gap: 10px;'>"
    "                    <div class='flex flex-col items-center justify-center'>"
    "                        <p>Current</p>"
    "                        <div class='info flex items-center justify-center'>"
    "                            <p id='current'> &&current </p>"
    "                        </div>"
    "                    </div>"
    "                   &&sButton"
    "                </div>"
    "            </div>"
    "            <div class='flex items-center p-min' style='gap: 5px;'>"
    "                <form action='set' method='get'   class='flex flex-1 items-center' style='justify-content: space-around; gap: 5px;'>"
    "                        <div class='flex flex-col items-center justify-center'>"
    "                            <input id='high' name='high' class='form-input' type='number' value='&&high'/>"
    "                            <p>High</p>"
    "                        </div>"
    "                        <div class='flex flex-col items-center justify-center'>"
    "                            <input id='low' name='low' class='form-input' type='number' value='&&low'/>"
    "                            <p>Low</p>"
    "                        </div>"
        "                        <div class='flex flex-col items-center justify-center'>"
    "                            <input id='ready' name='ready' class='form-input' type='number' value='&&ready'/>"
    "                            <p>Ready</p>"
    "                        </div>"
    "                        <button class='button btn-red' type='submit' >"
    "                            Set"
    "                        </button>"
    "                </form>"
    "            </div>"
    "        </div>"
    "        <div class='border w-full container flex p-min'>"
    "            <h1 class='flex-1'>Liquid Level</h1>"
    "            <div class='flex flex items-center' style='justify-content: end;'>"
    "               &&lButton"
    "            </div>"
    "        </div>"
    "        <div class='flex-1'></div>"
    "        <div class='border w-full container flex p-min'>"
    "            <h1 class='flex-1'>Settings</h1>"
    "            <div class='flex  flex items-center' style='justify-content: end; gap: 10px;'>"
    "                <a href='restart'>"
    "                    <button class='button btn-white'>"
    "                        Restart"
    "                    </button>"
    "                </a>"
    "                <a href='settings'>"
    "                    <button class='button btn-wite'>"
    "                        Setup Wifi"
    "                    </button>"
    "                </a>"
    "            </div>"
    "        </div>"
    "    </div>"
    "</body>"
    "&&script"
    "</html>";

const String sOnButton =
    "<a href='sOn'>"
    "<button class='button btn-green'>"
    "On"
    "</button>"
    "</a>";

const String sOffButton =
    "<a href='sOff'>"
    "    <button class='button btn-red'>"
    "        Off"
    "    </button>"
    "</a>";

const String lOffButton =
    "<a href='lOff'>"
    "    <button class='button btn-red'>"
    "        Off"
    "    </button>"
    "</a>";

const String lOnButton =
    "<a href='lOn'>"
    "    <button class='button btn-green'>"
    "        On"
    "    </button>"
    "</a>";
const String script =
"<script>"
"    const showAlert = (sensorValue) => {"
"    const alertDiv = document.getElementById('alert');"
"    if(sensorValue.includes('Alarm Closed')) {"
"        alertDiv.style.display = 'hidden';"
"        return;"
"    };"
"        const sensor = parseFloat(sensorValue.replace(/\D+/gm, '').replace(/^\s+|\s+$/gm, ''));"
"        const lowInput = document.getElementById('low');"
"        const highInput = document.getElementById('high');"
"        const readyInput = document.getElementById('ready');"
"        const currentElement = document.getElementById('current');"
"        const low = parseFloat(lowInput.value);"
"        const high = parseFloat(highInput.value);"
"        const ready = parseFloat(readyInput.value);"
"        const sensorData = document.getElementById('sensorData');"
""
"        currentElement.innerText = sensor;"
""
"        if ((low >= high) || (ready >= high) || (ready <= low)) {"
"            alertDiv.style.backgroundColor = 'var(--red-500)';"
"            sensorData.innerText = `Something went wrong. Please Check your enterences!`;"
"            return;"
"        };"
"        if (Math.abs(ready-sensor) <= 2) {"
"            alertDiv.style.backgroundColor = 'var(--green-500)';"
"            sensorData.innerText = `It's Ready!`;"
"            return;"
"        };"
"        if (sensor < low) {"
"            alertDiv.style.backgroundColor = 'var(--yellow-400)';"
"            sensorData.innerText = `Sensor data is very low`;"
"        } else if (sensor > high) {"
"            alertDiv.style.backgroundColor = 'var(--red-500)';"
"            sensorData.innerText = `Sensor data is very high`;"

"        } else  {"
"            alertDiv.style.backgroundColor = 'var(--blue-400)';"
"            sensorData.innerText = `Sensor data is normal`;"
"        };"
"    };"
"    const getSensorValue = () => {"
"        const sensorDataElement = document.getElementById('sensorData');"
"        var xhr = new XMLHttpRequest();"
"        xhr.open('GET', 'getSensorValue', true);"
"        xhr.onreadystatechange = function () {"
"            if (xhr.readyState === 4 && xhr.status === 200) {"
"                var sensorValue = xhr.responseText;"
"                showAlert(sensorValue);"
"            } else {"
"                sensorDataElement.innerHTML = xhr.statusText + ' ' + xhr.responseText;"
"            }"
"        };"
"        xhr.onerror = function () {"
"            sensorDataElement.innerHTML = 'Request failed';"
"        };"
"        xhr.send();"
"    };"
"    window.onload = () => {"
"        document.getElementById('sensorData').innerHTML = 'page loaded';"
"        setInterval(getSensorValue, 1000);"
"    }"
"</script>";

String introductionPage =
"<html>"
"    <head>"
"        <meta charset='utf-8'>"
"        <meta name='viewport' content='width=device-width, initial-scale=1'>"
"        &&style"
"    </head>"
"    <body>"
"        <div class='h-max flex dark items-center flex-col main'>"
"            <h1 class='title'>Instructions</h1>"
"            <ul>"
"                <li>Click Setup wifi, set up the local wifi, it should show at the bottom connected!.</li>"
"                <li>Install the sensors.</li>"
"                <li>Put in Low and High range.</li>"
"                <li>Turn on the sensor alarms.</li>"
"                <li>Make sure you have notifications turned on your phone.</li>"
"            </ul>"
"            </div>"
"    </body>"
"</html>";


String settingsPage=

"<html>"
"    <head>"
"        <meta charset='utf-8'>"
"        <meta name='viewport' content='width=device-width, initial-scale=1'>"
"    </head>"
"    <body>"
"        <form action='savesettings' method='get' class='h-max flex dark items-center flex-col main'>"
"            <h1 class='title'>Settings</h1>"
"            <div class='flex flex-col w-full' style='gap: 5px; '>"
"                <label>Ssid</label>"
"                <input name='ssid' class='form-input p-min' value='&&ssid' style='width: 100%;' />"
"            </div>"
"            <div class='flex flex-col w-full' style='gap: 5px;'>"
"                <label>Password</label>"
"                <input name='pwd' class='form-input p-min' value='&&pwd' style='width: 100%;' />"
"            </div>"
// "                <input type='checkbox' id='mode' name='mode' value='AP&'>"
// "                <label for='mode' AP mode</label><br>"
"            <button type='submit' class='button btn-green'>Save</button>"
"        </div>"
"    </body>"
"</html>";

